name: kubernets

on:
  workflow_call:

jobs:
  EKS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: AWS credential configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
          aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
          aws-region: us-east-2
          
      - run: git clone https://github.com/pedro162/Infra_CI.git
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - run: terraform -chdir=Infra_CI/env/Hmolog init

      - run: terraform -chdir=Infra_CI/env/Hmolog destroy -auto-approve

      - run: terraform -chdir=Infra_CI/env/Hmolog apply -auto-approve
      
      - run: echo "$(terraform -chdir=Infra_CI/env/Hmolog output -raw IP_db)"
        id: URL

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
      
      - run: aws sts get-caller-identity
      
      - run: aws eks update-kubeconfig --region us-west-2 --name homolog2

      - run: kubectl get svc

      - run: kubectl create secret generic dbhost --from-literal=HOST=${{steps.URL.output.stdout}}
      - run: kubectl create secret generic dbport --from-literal=DBPORT=${{secrets.DBPORT}}
      - run: kubectl create secret generic dbuser --from-literal=USER=${{secrets.DBUSER}}
      - run: kubectl create secret generic dbpassword --from-literal=PASSWORD=${{secrets.DBPASSWORD}}
      - run: kubectl create secret generic dbname --from-literal=DBNAME=${{secrets.DBNAME}}
      - run: kubectl create secret generic port --from-literal=PORT=8000

      - run: terraform -chdir=Infra_CI/env/Hmolog destroy -auto-approve
      
